sudo: required
dist: trusty

language: haxe

haxe:
  - "3.2.0"
  - "3.4.0"
  - "3.4.1"
  - "3.4.2"
  - "3.4.4"
  - "3.4.7"
  - "development"

matrix:
  allow_failures:
    - haxe: development

script:
  - haxe build.hxml

deploy:
  - provider: script
    haxe: 3.4.7
    script: bash ./releaseHaxelib.sh $HAXELIB_PWD
    on:
      tags: true